class Tweet
  @account_verify_credentials = {
      "contributors_enabled": true, 
      "created_at": "Sat May 09 17:58:22 +0000 2009", 
      "default_profile": false, 
      "default_profile_image": false, 
      "description": "I taught your phone that thing you like.  The Mobile Partner Engineer @Twitter. ", 
      "favourites_count": 588, 
      "follow_request_sent": null, 
      "followers_count": 10625, 
      "following": null, 
      "friends_count": 1181, 
      "geo_enabled": true, 
      "id": 38895958, 
      "id_str": "38895958", 
      "is_translator": false, 
      "lang": "en", 
      "listed_count": 190, 
      "location": "San Francisco", 
      "name": "Sean Cook", 
      "notifications": null, 
      "profile_background_color": "1A1B1F", 
      "profile_background_image_url": "http://a0.twimg.com/profile_background_images/495742332/purty_wood.png", 
      "profile_background_image_url_https": "https://si0.twimg.com/profile_background_images/495742332/purty_wood.png", 
      "profile_background_tile": true, 
      "profile_image_url": "http://a0.twimg.com/profile_images/1751506047/dead_sexy_normal.JPG", 
      "profile_image_url_https": "https://si0.twimg.com/profile_images/1751506047/dead_sexy_normal.JPG", 
      "profile_link_color": "2FC2EF", 
      "profile_sidebar_border_color": "181A1E", 
      "profile_sidebar_fill_color": "252429", 
      "profile_text_color": "666666", 
      "profile_use_background_image": true, 
      "protected": false, 
      "screen_name": "Hubot", 
      "show_all_inline_media": true, 
      "status": {
          "contributors": null, 
          "coordinates": {
              "coordinates": [
                  -122.45037293, 
                  37.76484123
              ], 
              "type": "Point"
          }, 
          "created_at": "Tue Aug 28 05:44:24 +0000 2012", 
          "favorited": false, 
          "geo": {
              "coordinates": [
                  37.76484123, 
                  -122.45037293
              ], 
              "type": "Point"
          }, 
          "id": 240323931419062272, 
          "id_str": "240323931419062272", 
          "in_reply_to_screen_name": "messl", 
          "in_reply_to_status_id": 240316959173009410, 
          "in_reply_to_status_id_str": "240316959173009410", 
          "in_reply_to_user_id": 18707866, 
          "in_reply_to_user_id_str": "18707866", 
          "place": {
              "attributes": {}, 
              "bounding_box": {
                  "coordinates": [
                      [
                          [
                              -122.45778216, 
                              37.75932999
                          ], 
                          [
                              -122.44248216, 
                              37.75932999
                          ], 
                          [
                              -122.44248216, 
                              37.76752899
                          ], 
                          [
                              -122.45778216, 
                              37.76752899
                          ]
                      ]
                  ], 
                  "type": "Polygon"
              }, 
              "country": "United States", 
              "country_code": "US", 
              "full_name": "Ashbury Heights, San Francisco", 
              "id": "866269c983527d5a", 
              "name": "Ashbury Heights", 
              "place_type": "neighborhood", 
              "url": "http://api.twitter.com/1/geo/id/866269c983527d5a.json"
          }, 
          "retweet_count": 0, 
          "retweeted": false, 
          "source": "<a href=\"http://twitter.com\" rel=\"nofollow\">Twitter for  iPhone</a>", 
          "text": "@messl congrats! So happy for all 3 of you.", 
          "truncated": false
      }, 
      "statuses_count": 2609, 
      "time_zone": "Pacific Time (US & Canada)", 
      "url": null, 
      "utc_offset": -28800, 
      "verified": false
  }

  @tweet = {
    created_at: 'Sun Jun 22 06:56:26 +0000 2014',
    id: 480605213426860000,
    id_str: '480605213426860032',
    text: 'test .',
    source: '<a href="http://twitter.com" rel="nofollow">Twitter Web Client</a>',
    truncated: false,
    in_reply_to_status_id: null,
    in_reply_to_status_id_str: null,
    in_reply_to_user_id: null,
    in_reply_to_user_id_str: null,
    in_reply_to_screen_name: null,
    user: { 
       id: 416981850,
       id_str: '416981850',
       name: 'エイトース',
       screen_name: 'ju_no89',
       location: '',
       url: null,
       description: null,
       protected: false,
       followers_count: 6,
       friends_count: 4,
       listed_count: 0,
       created_at: 'Sun Nov 20 11:14:33 +0000 2011',
       favourites_count: 102,
       utc_offset: -36000,
       time_zone: 'Hawaii',
       geo_enabled: false,
       verified: false,
       statuses_count: 44,
       lang: 'ja',
       contributors_enabled: false,
       is_translator: false,
       is_translation_enabled: false,
       profile_background_color: 'C0DEED',
       profile_background_image_url: 'http://abs.twimg.com/images/themes/theme1/bg.png',
       profile_background_image_url_https: 'https://abs.twimg.com/images/themes/theme1/bg.png',
       profile_background_tile: false,
       profile_image_url: 'http://abs.twimg.com/sticky/default_profile_images/default_profile_5_normal.png',
       profile_image_url_https: 'https://abs.twimg.com/sticky/default_profile_images/default_profile_5_normal.png',
       profile_link_color: '0084B4',
       profile_sidebar_border_color: 'C0DEED',
       profile_sidebar_fill_color: 'DDEEF6',
       profile_text_color: '333333',
       profile_use_background_image: true,
       default_profile: true,
       default_profile_image: true,
       following: null,
       follow_request_sent: null,
       notifications: null 
    },
    geo: null,
    coordinates: null,
    place: null,
    contributors: null,
    retweet_count: 0,
    favorite_count: 0,
    entities: { hashtags: [], symbols: [], urls: [], user_mentions: [] },
    favorited: false,
    retweeted: false,
    filter_level: 'medium',
    lang: 'und',
    timestamp: 1403420186756 
  }

  @directMessage = { 
    direct_message: { 
      id: 480454960484593660,
      id_str: '480454960484593665',
      text: 'time',
      sender: { 
        id: 416981850,
        id_str: '416981850',
        name: 'エイトース',
        screen_name: 'ju_no89',
        location: null,
        url: null,
        description: null,
        protected: false,
        followers_count: 6,
        friends_count: 4,
        listed_count: 0,
        created_at: 'Sun Nov 20 11:14:33 +0000 2011',
        favourites_count: 102,
        utc_offset: -36000,
        time_zone: 'Hawaii',
        geo_enabled: false,
        verified: false,
        statuses_count: 41,
        lang: 'ja',
        contributors_enabled: false,
        is_translator: false,
        is_translation_enabled: false,
        profile_background_color: 'C0DEED',
        profile_background_image_url: 'http://abs.twimg.com/images/themes/theme1/bg.png',
        profile_background_image_url_https: 'https://abs.twimg.com/images/themes/theme1/bg.png',
        profile_background_tile: false,
        profile_image_url: 'http://abs.twimg.com/sticky/default_profile_images/default_profile_5_normal.png',
        profile_image_url_https: 'https://abs.twimg.com/sticky/default_profile_images/default_profile_5_normal.png',
        profile_link_color: '0084B4',
        profile_sidebar_border_color: 'C0DEED',
        profile_sidebar_fill_color: 'DDEEF6',
        profile_text_color: '333333',
        profile_use_background_image: true,
        default_profile: true,
        default_profile_image: true,
        following: false,
        follow_request_sent: false,
        notifications: false 
      },
      sender_id: 416981850,
      sender_id_str: '416981850',
      sender_screen_name: 'ju_no89',
      recipient: { 
        id: 1147048278,
        id_str: '1147048278',
        name: '部室なう！',
        screen_name: 'busitu_now',
        location: null,
        url: null,
        description: null,
        protected: true,
        followers_count: 18,
        friends_count: 2,
        listed_count: 0,
        created_at: 'Mon Feb 04 04:50:57 +0000 2013',
        favourites_count: 1,
        utc_offset: 32400,
        time_zone: 'Irkutsk',
        geo_enabled: false,
        verified: false,
        statuses_count: 3492,
        lang: 'ja',
        contributors_enabled: false,
        is_translator: false,
        is_translation_enabled: false,
        profile_background_color: 'C0DEED',
        profile_background_image_url: 'http://abs.twimg.com/images/themes/theme1/bg.png',
        profile_background_image_url_https: 'https://abs.twimg.com/images/themes/theme1/bg.png',
        profile_background_tile: false,
        profile_image_url: 'http://pbs.twimg.com/profile_images/3735637586/bb9facf4f30fba0ebf4b0a9c073e9b75_normal.png',
        profile_image_url_https: 'https://pbs.twimg.com/profile_images/3735637586/bb9facf4f30fba0ebf4b0a9c073e9b75_normal.png',
        profile_link_color: '0084B4',
        profile_sidebar_border_color: 'C0DEED',
        profile_sidebar_fill_color: 'DDEEF6',
        profile_text_color: '333333',
        profile_use_background_image: true,
        default_profile: true,
        default_profile_image: false,
        following: false,
        follow_request_sent: false,
        notifications: false 
      },
      recipient_id: 1147048278,
      recipient_id_str: '1147048278',
      recipient_screen_name: 'busitu_now',
      created_at: 'Sat Jun 21 20:59:23 +0000 2014',
      entities: { hashtags: [], symbols: [], urls: [], user_mentions: [] }
    }
  }

  @favorite = { 
  event: 'favorite',
  created_at: 'Sun Jun 22 16:20:09 +0000 2014',
  source: { 
     id: 19368158,
     id_str: '19368158',
     name: 'ATOK',
     screen_name: 'hoo89',
     location: '京都 or 呉鎮守府',
     url: null,
     description: '京都の情報工学徒 紙面上は4回生',
     protected: false,
     followers_count: 100,
     friends_count: 90,
     listed_count: 7,
     created_at: 'Thu Jan 22 23:09:01 +0000 2009',
     favourites_count: 4215,
     utc_offset: 32400,
     time_zone: 'Osaka',
     geo_enabled: true,
     verified: false,
     statuses_count: 6006,
     lang: 'ja',
     contributors_enabled: false,
     is_translator: false,
     is_translation_enabled: false,
     profile_background_color: 'C7EAE5',
     profile_background_image_url: 'http://pbs.twimg.com/profile_background_images/378800000088533611/c12eea0b67b9e727b186356ad71df89e.png',
     profile_background_image_url_https: 'https://pbs.twimg.com/profile_background_images/378800000088533611/c12eea0b67b9e727b186356ad71df89e.png',
     profile_background_tile: true,
     profile_image_url: 'http://pbs.twimg.com/profile_images/451005987734831105/BDFMLSAY_normal.png',
     profile_image_url_https: 'https://pbs.twimg.com/profile_images/451005987734831105/BDFMLSAY_normal.png',
     profile_banner_url: 'https://pbs.twimg.com/profile_banners/19368158/1398592901',
     profile_link_color: '01665E',
     profile_sidebar_border_color: 'FFFFFF',
     profile_sidebar_fill_color: '99CC33',
     profile_text_color: '3E4415',
     profile_use_background_image: true,
     default_profile: false,
     default_profile_image: false,
     following: null,
     follow_request_sent: null,
     notifications: null },
  target: { 
     id: 1147048278,
     id_str: '1147048278',
     name: '部室なう！',
     screen_name: 'busitu_now',
     location: null,
     url: null,
     description: null,
     protected: true,
     followers_count: 18,
     friends_count: 2,
     listed_count: 0,
     created_at: 'Mon Feb 04 04:50:57 +0000 2013',
     favourites_count: 1,
     utc_offset: 32400,
     time_zone: 'Irkutsk',
     geo_enabled: false,
     verified: false,
     statuses_count: 3493,
     lang: 'ja',
     contributors_enabled: false,
     is_translator: false,
     is_translation_enabled: false,
     profile_background_color: 'C0DEED',
     profile_background_image_url: 'http://abs.twimg.com/images/themes/theme1/bg.png',
     profile_background_image_url_https: 'https://abs.twimg.com/images/themes/theme1/bg.png',
     profile_background_tile: false,
     profile_image_url: 'http://pbs.twimg.com/profile_images/3735637586/bb9facf4f30fba0ebf4b0a9c073e9b75_normal.png',
     profile_image_url_https: 'https://pbs.twimg.com/profile_images/3735637586/bb9facf4f30fba0ebf4b0a9c073e9b75_normal.png',
     profile_link_color: '0084B4',
     profile_sidebar_border_color: 'C0DEED',
     profile_sidebar_fill_color: 'DDEEF6',
     profile_text_color: '333333',
     profile_use_background_image: true,
     default_profile: true,
     default_profile_image: false,
     following: null,
     follow_request_sent: null,
     notifications: null },
  target_object: { 
     created_at: 'Sat Jun 21 20:51:52 +0000 2014',
     id: 480453067884593150,
     id_str: '480453067884593152',
     text: 'Server time is: Sun Jun 22 2014 05:51:51 GMT+0900 (JST)',
     source: '<a href="http://www.kitcc.org/" rel="nofollow">部室なう 2.0</a>',
     truncated: false,
     in_reply_to_status_id: null,
     in_reply_to_status_id_str: null,
     in_reply_to_user_id: null,
     in_reply_to_user_id_str: null,
     in_reply_to_screen_name: null,
     user: { 
        id: 1147048278,
        id_str: '1147048278',
        name: '部室なう！',
        screen_name: 'busitu_now',
        location: null,
        url: null,
        description: null,
        protected: true,
        followers_count: 18,
        friends_count: 2,
        listed_count: 0,
        created_at: 'Mon Feb 04 04:50:57 +0000 2013',
        favourites_count: 1,
        utc_offset: 32400,
        time_zone: 'Irkutsk',
        geo_enabled: false,
        verified: false,
        statuses_count: 3493,
        lang: 'ja',
        contributors_enabled: false,
        is_translator: false,
        is_translation_enabled: false,
        profile_background_color: 'C0DEED',
        profile_background_image_url: 'http://abs.twimg.com/images/themes/theme1/bg.png',
        profile_background_image_url_https: 'https://abs.twimg.com/images/themes/theme1/bg.png',
        profile_background_tile: false,
        profile_image_url: 'http://pbs.twimg.com/profile_images/3735637586/bb9facf4f30fba0ebf4b0a9c073e9b75_normal.png',
        profile_image_url_https: 'https://pbs.twimg.com/profile_images/3735637586/bb9facf4f30fba0ebf4b0a9c073e9b75_normal.png',
        profile_link_color: '0084B4',
        profile_sidebar_border_color: 'C0DEED',
        profile_sidebar_fill_color: 'DDEEF6',
        profile_text_color: '333333',
        profile_use_background_image: true,
        default_profile: true,
        default_profile_image: false,
        following: null,
        follow_request_sent: null,
        notifications: null },
     geo: null,
     coordinates: null,
     place: null,
     contributors: null,
     retweet_count: 0,
     favorite_count: 1,
     entities: { hashtags: [], symbols: [], urls: [], user_mentions: [] },
     favorited: false,
     retweeted: false,
     lang: 'en' } }

module.exports = Tweet